# Generated by Django 6.0.1 on 2026-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("HIGH", "high"), ("MEDIUM", "medium"), ("LOW", "low")],
                default="MEDIUM",
                max_length=20,
            ),
        ),
    ]
