# Generated by Django 6.0.1 on 2026-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
