# Generated by Django 6.0.1 on 2026-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_task_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
